# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Griffin Steffy
title: Embedded Systems Engineer
email: griffinsteffy19@gmail.com
website: www.griffinsteffy.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: griffin.steffy
linkedin_username: griffinsteffy
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: griffin.steffy
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/resume-profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Griffin and I'm an embedded computer engineer. As well as embedded systems systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Software Design</mark> and <mark>Eating Pizza</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
      # - layout: top-middle
      #   title: Super awesome project
      #   link: github.com/sproogen
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  sproogen/modern-resume-theme
      #       icon: fab fa-github
      #       url: github.com/sproogen/modern-resume-theme
      #   quote: >
      #     This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
      #   description: | # this will include new lines to allow paragraphs
      #     I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lead Software Engineer
        link: www.crowndesigngroup.org
        caption: December 2022 - Present
        quote: >
          Inovating in the camera operator space, prioritizing the mobility user experience.
        description: | # this will include new lines to allow paragraphs
          I designed, wrote, and tested the full system software for the Crown Design Group's camera operator system. I worked with a team of 2 other engineers to come up with the hardware design and enclosure. I also worked with the customer to make sure the system met their needs, through the initial pilot phase.

      - layout: left
        title: Embedded Engineer
        link: meshsystems.com
        caption: October 2021 - Present
      - layout: left
        title: Electrical Engineer II
        link: milwaukeetool.com

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rose-Hulman Institute of Technology
        caption: 2015 - 2019
        sub_title: BSc Computer Engineering
        description: | # this will include new lines to allow paragraphs
          During my time at Rose-Hulman I learned the necessary technical skills to become a computer engineer, but more importantly I learned how to learn. I am now able to pick up new skills and technologies quickly and efficiently.

          I gained import leadership skills through my time on the Football team, and as a member of the board at my Fraternity.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Video Editing
      - Ultimate Frisbee
      - Working Out
      - Grilling
      - Playing with my family of 4 plus our dog Freddie

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
